remote_theme: "mmistakes/minimal-mistakes@4.23.0"
minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
title: "Story Template Custom Record Templates Documentation"
search: true
search_full_content: true
plugins:
  - jekyll-include-cache
defaults:
  - values:
      show_date: true
      layout: single
      classes: wide
      sidebar:
        - title: "Extension Documentation"
          text: "Documentation for the Story Template Custom Record Templates extension for Fantasy Grounds"
        - nav: "docs"
